### ISSUE TITLE
[Feature Request] Optionally specify a single table to convert

### ISSUE THREAD

**Issue by 12345ieee** [darrentu/convert-db-to-csv#1]
Title says it all.

Thank you for this tool.

**Comment by darrentu** [comment]
Hey Andrea,

Thank you for the encouragement. 
I will definitely consider working on the single table conversion after my midterms.

Darren

**Comment by darrentu** [comment]
@12345ieee Sorry for the late reply. Is there a solid use case as to why there is a need to optionally specify a single table?

**Comment by 12345ieee** [comment]
As you can imagine, I don't remember anymore.

Feel free to close this.

**Comment by darrentu** [comment]
@12345ieee Sorry about that.

**Comment by jcguu95** [comment]
Anyway, it is a pleasant little script. Thank you very much!
