### ISSUE TITLE
Doesn't do anything

### ISSUE THREAD

**Issue by quantumgolem** [darrentu/convert-db-to-csv#2]
I tried running `./convert-db-to-csv.sh example.db`, but it didn't create anything. It didn't give any messages, either. It was completely silent.

**Comment by darrentu** [comment]
Would it be ok for you to provide a link to example.db? ./convert-db-to-csv.sh should work on all db files.

**Comment by quantumgolem** [comment]
Sorry I forgot what I was trying to convert. I'm just using a GUI application for this now. Thanks!
